version: '3.8'

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bhxh_galaxy
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1

    restart: always